---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.20.3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: .venv/bin/python3 -m ansiblelint
        exclude: ^\..*\.(yml|yaml)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
