---
- name: "cron_jobs | Create cron jobs directory"
  ansible.builtin.file:
    path: "{{ openwrt_cron_scripts_dir }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx"

- name: "cron_jobs | Get localhost user group id"
  ansible.builtin.command:
    cmd: "id -g {{ lookup('env', 'USER') }}"
  delegate_to: localhost
  register: localhost_user_gid
  check_mode: false
  changed_when: false

- name: cron_jobs | Template block
  ansible.builtin.copy:
    dest: /tmp/{{ inventory_hostname_short | upper }}_{{ item.name | lower }}.sh.j2
    content: "{{ item.job }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ localhost_user_gid.stdout }}"
    mode: "u=rw,g=rw"
  loop: "{{ openwrt_cron_jobs }}"
  delegate_to: localhost
  check_mode: false

- name: "cron_jobs | Copy scripts"
  ansible.builtin.template:
    dest: "{{ openwrt_cron_scripts_dir }}/{{ item.name | lower }}.sh"
    src: "/tmp/{{ inventory_hostname_short | upper }}_{{ item.name | lower }}.sh.j2"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx"
  loop: "{{ openwrt_cron_jobs }}"

- name: cron_jobs | Configure cron job(s)
  ansible.builtin.lineinfile:
    path: "/etc/crontabs/root"
    regexp: "{{ openwrt_cron_scripts_dir }}/{{ item.name | lower }}\\.sh$"
    line: >
      {{ item.minute | default("*") }}
      {{ item.hour | default("*") }}
      {{ item.day | default("*") }}
      {{ item.month | default("*") }}
      {{ item.weekday | default("*") }}
      {{ openwrt_cron_scripts_dir }}/{{ item.name | lower }}.sh
  loop: "{{ openwrt_cron_jobs }}"
  notify: "Restart cron"
