---
- name: "Show role configuration information"
  ansible.builtin.debug:
    msg: |
      # Device configuration
      openwrt_id:       "{{ openwrt_id }}"
      openwrt_platform: "{{ openwrt_platform }}"
      openwrt_version:  "{{ openwrt_version }}"

      openwrt_version_upgrade_enabled: "{{ openwrt_version_upgrade_enabled }}"

      # Services
      openwrt_disabled_services:
      {{ openwrt_disabled_services | to_nice_yaml }}
      openwrt_enabled_services:
      {{ openwrt_enabled_services | to_nice_yaml }}

      # Packages
      openwrt_packages_upgrade_enabled:         {{ openwrt_packages_upgrade_enabled }}
      openwrt_packages_upgrade_reboot_enabled:  {{ openwrt_packages_upgrade_reboot_enabled }}
      openwrt_packages_upgrade_excluded:
      {{ openwrt_packages_upgrade_excluded | to_nice_yaml }}
      openwrt_installed_packages:
      {{ openwrt_installed_packages | to_nice_yaml }}
      openwrt_uninstalled_packages:
      {{ openwrt_uninstalled_packages | to_nice_yaml }}

      # Back-up
      openwrt_back_up_enabled:    {{ openwrt_back_up_enabled }}
      openwrt_back_up_local_dir:  {{ openwrt_back_up_local_dir }}

      # Other
      openwrt_disk_resize_enabled: "{{ openwrt_disk_resize_enabled }}"
      openwrt_ssh_public_key: {{ openwrt_ssh_public_key }}

- name: "Manage prerequisites"
  ansible.builtin.import_tasks: "prerequisites.yaml"

- name: "Manage back-up"
  ansible.builtin.include_tasks: "back_up.yaml"
  when: openwrt_back_up_enabled

- name: "Update image"
  ansible.builtin.include_tasks: "update_version.yaml"
  when: openwrt_version_upgrade_enabled

- name: "Resize disk"
  ansible.builtin.include_tasks: "disk_resize.yaml"
  when: openwrt_disk_resize_enabled

- name: "Add SSH public key"
  ansible.builtin.include_tasks: "ssh_add_keys.yaml"
  when: openwrt_ssh_public_key

- name: "Manage packages"
  ansible.builtin.import_tasks: "packages.yaml"

- name: "Manage services"
  ansible.builtin.import_tasks: "services.yaml"
