---
# Ensure services are managed
- name: "services | Enable services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ openwrt_enabled_services }}"

- name: "services | Disable services"
  failed_when: false
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ openwrt_disabled_services }}"
