---
- name: "Reboot device"
  ansible.builtin.command:
    cmd: reboot
  changed_when: true

- name: "Wait for device"
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600

- name: "Update opkg cache"
  community.general.opkg:
    name: ~  # noqa args[module]
    update_cache: true
  changed_when: false
  when: not ansible_check_mode
  register: prerequisites_opkg_cache_update
  failed_when:
    - '"False: Unknown package" not in prerequisites_opkg_cache_update.msg'
