---
- name: "Reboot device"
  ansible.builtin.command:
    cmd: reboot
  changed_when: true

- name: "Wait for device"
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600
